### ISSUE TITLE
Issue with importing to JATOS

### ISSUE THREAD

**Issue by fodjf33** [celstark/oMST#2]
After downloading the oMST-main.zip file and clicking Import Study in JATOS, I keep getting an error message "Import of study failed: Study is invalid". I was wondering if anyone else had a similar issue or has any tips for importing into JATOS.

**Comment by celstark** [comment]
Do you mean `omst.jzip` from the Release page here?
https://github.com/celstark/oMST/releases/tag/v1.0

**Comment by fodjf33** [comment]
Fixed it - thank you!
